import botd from '../assets/icons/botd.svg';
import fs from '../assets/icons/fs.svg';
import sp from '../assets/icons/sp.svg';
import cf from '../assets/icons/cf.svg';
import xd from '../assets/icons/xd.svg';
import ae from '../assets/icons/ae.svg';
import sketch from '../assets/icons/sketch.svg';
import indesign from '../assets/icons/indesign.svg';
import figma from '../assets/icons/figma.svg';
import logo from '../assets/img/logo.png';
import user from '../assets/img/user.jpg';

const botdImg = document.querySelector('#botd');
botdImg.src = botd;
const fsImg = document.querySelector('#fs');
fsImg.src = fs;
const spImg = document.querySelector('#sp');
spImg.src = sp;
const cfImg = document.querySelector('#cf');
cfImg.src = cf;
const xdImg = document.querySelector('#xd');
xdImg.src = xd;
const aeImg = document.querySelector('#ae');
aeImg.src = ae;
const sketchImg = document.querySelector('#sketch');
sketchImg.src = sketch;
const indesignImg = document.querySelector('#indesign');
indesignImg.src = indesign;
const figmaImg = document.querySelector('#figma');
figmaImg.src = figma;
const logoImg = document.querySelector('#logo');
logoImg.src = logo;
const userImg = document.querySelector('#user');
userImg.src = user;